### ISSUE TITLE
Practical example in README

### ISSUE THREAD

**Issue by mattstauffer** [zaengle/pipeline#1]
Hey friends! I'm super excited to check this out!

Could you build an example using real world code for maybe a pipeline with two pipes and real data in the traveler? I think that would both help people learn how to use this pattern in general, and also make it clear how this particular implementation works.

Thanks!!

**Comment by jesseschutt** [comment]
@mattstauffer - What do you think about this? https://github.com/zaengle/pipeline/commit/f9c58a9db043d3b47a402ab948b75478f109c892

**Comment by mattstauffer** [comment]
Jesse, you’ll have to excuse my delay. Life is crazy. If I have ideas for anything else example-wise I’ll be sure to open a new issue. Thanks for addressing it so quickly!
